function choice = selectdataset

    d = dialog('Position',[300 300 250 150],'Name','Select Data Set');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 210 40],...
           'String','Enter Type Obj Func');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 70 150 25],...
           'String',{'kroA100';'kroB100';'kroB150';'kroA150';'kroB200';'kroA200'},...
           'Callback',@popup_callback);
       
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Select',...
           'Callback','delete(gcf)');
       
    choice = 'kroA100';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,callbackdata)
          idx = popup.Value;
          popup_items = popup.String;
          choice = char(popup_items(idx,:));
       end
end